[{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2448",
	"severity": 8,
	"message": "Block-scoped variable 'syncStatus' used before its declaration.",
	"source": "ts",
	"startLineNumber": 121,
	"startColumn": 9,
	"endLineNumber": 121,
	"endColumn": 19,
	"relatedInformation": [
		{
			"startLineNumber": 142,
			"startColumn": 14,
			"endLineNumber": 142,
			"endColumn": 24,
			"message": "'syncStatus' is declared here.",
			"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts"
		}
	],
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2454",
	"severity": 8,
	"message": "Variable 'syncStatus' is used before being assigned.",
	"source": "ts",
	"startLineNumber": 121,
	"startColumn": 9,
	"endLineNumber": 121,
	"endColumn": 19,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2448",
	"severity": 8,
	"message": "Block-scoped variable 'syncStatus' used before its declaration.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 9,
	"endLineNumber": 122,
	"endColumn": 19,
	"relatedInformation": [
		{
			"startLineNumber": 142,
			"startColumn": 14,
			"endLineNumber": 142,
			"endColumn": 24,
			"message": "'syncStatus' is declared here.",
			"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts"
		}
	],
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2454",
	"severity": 8,
	"message": "Variable 'syncStatus' is used before being assigned.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 9,
	"endLineNumber": 122,
	"endColumn": 19,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2448",
	"severity": 8,
	"message": "Block-scoped variable 'syncStatus' used before its declaration.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 43,
	"endLineNumber": 122,
	"endColumn": 53,
	"relatedInformation": [
		{
			"startLineNumber": 142,
			"startColumn": 14,
			"endLineNumber": 142,
			"endColumn": 24,
			"message": "'syncStatus' is declared here.",
			"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts"
		}
	],
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2454",
	"severity": 8,
	"message": "Variable 'syncStatus' is used before being assigned.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 43,
	"endLineNumber": 122,
	"endColumn": 53,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2448",
	"severity": 8,
	"message": "Block-scoped variable 'syncStatus' used before its declaration.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 72,
	"endLineNumber": 122,
	"endColumn": 82,
	"relatedInformation": [
		{
			"startLineNumber": 142,
			"startColumn": 14,
			"endLineNumber": 142,
			"endColumn": 24,
			"message": "'syncStatus' is declared here.",
			"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts"
		}
	],
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "2454",
	"severity": 8,
	"message": "Variable 'syncStatus' is used before being assigned.",
	"source": "ts",
	"startLineNumber": 122,
	"startColumn": 72,
	"endLineNumber": 122,
	"endColumn": 82,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1232",
	"severity": 8,
	"message": "An import declaration can only be used at the top level of a namespace or module.",
	"source": "ts",
	"startLineNumber": 128,
	"startColumn": 7,
	"endLineNumber": 128,
	"endColumn": 13,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1232",
	"severity": 8,
	"message": "An import declaration can only be used at the top level of a namespace or module.",
	"source": "ts",
	"startLineNumber": 129,
	"startColumn": 1,
	"endLineNumber": 129,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1232",
	"severity": 8,
	"message": "An import declaration can only be used at the top level of a namespace or module.",
	"source": "ts",
	"startLineNumber": 133,
	"startColumn": 1,
	"endLineNumber": 133,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1232",
	"severity": 8,
	"message": "An import declaration can only be used at the top level of a namespace or module.",
	"source": "ts",
	"startLineNumber": 138,
	"startColumn": 1,
	"endLineNumber": 138,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1184",
	"severity": 8,
	"message": "Modifiers cannot appear here.",
	"source": "ts",
	"startLineNumber": 142,
	"startColumn": 1,
	"endLineNumber": 142,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1184",
	"severity": 8,
	"message": "Modifiers cannot appear here.",
	"source": "ts",
	"startLineNumber": 155,
	"startColumn": 1,
	"endLineNumber": 155,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1184",
	"severity": 8,
	"message": "Modifiers cannot appear here.",
	"source": "ts",
	"startLineNumber": 165,
	"startColumn": 1,
	"endLineNumber": 165,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "1184",
	"severity": 8,
	"message": "Modifiers cannot appear here.",
	"source": "ts",
	"startLineNumber": 215,
	"startColumn": 1,
	"endLineNumber": 215,
	"endColumn": 7,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ks2/antigravity/Remix-Nexus-POS-Pro/src/services/SupabaseSync.ts",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'row' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 327,
	"startColumn": 22,
	"endLineNumber": 327,
	"endColumn": 25,
	"modelVersionId": 5,
	"origin": "extHost1"
}]